### ISSUE TITLE
beampy.examples.example_kerr() will Lead to infinite loop..

### ISSUE THREAD

**Issue by charles-fischer** [Python-simulation/Beampy#3]
Hi Jonathan,

I'm trying to use the Beampy. And when I run this code example "beampy.examples.example_kerr()". It will go to loop

![Error message_kerr](https://user-images.githubusercontent.com/63844827/98759069-38232680-240b-11eb-8295-68f912f59197.JPG)

**Comment by Python-simulation** [comment]
Hi, thanks you for your interest in Beampy. This example compute over 2000 steps using 4 different methods. If you want to stop it before 2000 steps, you can change the value of the parameter "nbr_step" at line 335 in the file examples.py. Similarly, you can change the parameters "length_z" and "dist_z" to reduce the propagation length or the numerical precision between each steps.
Please tell me if this explanation answer your concern.

**Comment by charles-fischer** [comment]
Hi , Yes. After I send you the reply, I find it circulate after 2000 steps.
