### ISSUE TITLE
Can I use beampy to calculate beam parameter with different optics

### ISSUE THREAD

**Issue by charles-fischer** [Python-simulation/Beampy#4]
Dear Jonathan,

I tried using Beampy and It can used to describe beam profile with certain waveguide, like a fiber. 
And I'm wondering if it can be used to simulate beam propagation after different optics.
For example, a laser beam of BPP = 2mm*mrad, Initial beam waist = 0.1mm, After length of 100mm, there's a len(f=150mm); then after 200mm, there's a lens(f=-100mm), etc. 
What's the waist position and waist diameter after those optics. Can I use Beampy to simulate.
Thanks in advance.
Thank you for sharing Beampy.

Best regards.

**Comment by Python-simulation** [comment]
Unfortunately the basic beam propagation method makes the paraxial approximation and don't allow large angle variations that could occurs with lenses. You should look into "wide-angle BPM" or "Ray transfer matrix analysis" to use lenses in your design.
However, it is possible to incorporate lenses in the propagation if you use small enough lenses that don't violates the paraxial approximation and small index variation. One method consists of setting an array of varying index like in the paper https://doi.org/10.1364/AO.29.005064 or in the python module https://diffractio.readthedocs.io/en/latest/source/examples/optics/lenses.html
I hope that you will find the informations needed to realize your design.

**Comment by charles-fischer** [comment]
Hello Jonathan, 
Thanks for your feedback and sharing. I‘m trying to design program which can describe the laser beam propagation after certain optical system.
Like raw laser beam: waist, divergence. after several optical system, ABCD matrix, it will become another waist, divergence. But I just start using python, and it take efforts to to such a task.

**Comment by Python-simulation** [comment]
Hello Charles,
If I understand correctly your goal, I suggest you to look into opticspy: https://sterncat.github.io/files/Real_Ray_Tracing.html or into RayOptics: https://ray-optics.readthedocs.io/en/latest/examples/TripletExample.html
But I'm almost sure that Beampy and all BPM based solutions are not adapted to compute beam propagation through several optical systems.

**Comment by charles-fischer** [comment]
Hi Jonathan,
Thanks. I just check these two programs and they are very similar with ZEMAX. I will check it in detail.
You can close this issue.
Best regards.
