### ISSUE TITLE
It seems that only 2D simulation can be applied？

### ISSUE THREAD

**Issue by SkyLin1020** [Python-simulation/Beampy#5]

**Comment by Python-simulation** [comment]
Hello,
Yes indeed, Beampy is currently based on a 1+1D simulation (1 profil dimension and 1 propagation dimension).
I do not plan to implement a 2+1D simulation for now but maybe in the future.
In the mean time, I recommend you to check other packages like [this one](https://diffractio.readthedocs.io/en/latest/source/tutorial/scalar_XYZ/wpm-bpm%203d.html), to search for other solving method ([fdbpm](https://www.mathworks.com/matlabcentral/fileexchange/16102-finite-differences-beam-propagation-method-in-3-d), [fdtd](https://fdtd.readthedocs.io/en/latest/index.html)...) or to use commercial software like [Lumerical](https://www.lumerical.com/products/fdtd/) or [Rsoft](https://www.synopsys.com/photonic-solutions/rsoft-photonic-device-tools/rsoft-products.html).
Best regards, Jonathan.
